APPLICATION: jfkhome
ANSIBLE_USER: kevin
git_dir: /home/{{ ANSIBLE_USER }}/{{ APPLICATION }}
netbox_dns: netbox.thejfk.ca
web_dir: /var/www/html
env: "{{ custom_fields.dev_or_prod }}"
proxy_stats_url: https://ha{%- if env == 'dev' -%}-dev{%- endif -%}.thejfk.ca/;json